version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fileUpload
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:

