version: '3.8'

services:
  nodejs-lab:
    build: .
    container_name: nodejs-lab
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    networks:
      - nodejs-lab-network

networks:
  nodejs-lab-network:
    driver: bridge
