FROM php:8.1-apache

# Copy application files
COPY ./src /var/www/html/

# Enable MySQLi extension
RUN docker-php-ext-install mysqli

# Copy custom Apache configuration
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable Apache rewrite module
RUN a2enmod rewrite
